### ISSUE TITLE
[feature]添加自动匹配包名和签名配置的功能

### ISSUE THREAD

**Issue by jixiaoyong** [jixiaoyong/ApkSigner#10]
> 好想法，可以考虑添加这个功能。
> 
> 还没想好交互以及数据格式，比如使用json还是使用gradle中的格式，单个签名配置需要有如下信息：
> 
> ```
> storeFileAlias "" // APP自定义的属性“签名别名”，用来区分多个签名文件，下面其他参数与android项目中配置一致
> storeFile file('/path/to/key.keystore')
> storePassword 'pwd'
> keyAlias 'keyAlias'
> keyPassword 'pwd'
> ```

可以添加 包名和签名配置的功能吗？即选择apk 自动选择签名配置，这样就不用来回选择签名配置了

_Originally posted by @424385117 in https://github.com/jixiaoyong/ApkSigner/issues/9#issuecomment-2014540132_

**Comment by 424385117** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jixiaoyong** [comment]
使用方法：

如果需要根据apk文件的包名自动匹配之前使用的签名，需要在设置页面开启【是否自动匹配签名】并配置appt目录：

<img width="801" alt="image" src="https://github.com/jixiaoyong/ApkSigner/assets/18367427/3c3b98ac-4b95-4601-8a0e-f342b005d610">

这样在【签名APP】页面选择apk时就会默认自动匹配同一包名之前成功过的签名信息。

如果想切换为其他签名，选择修改签名即可：

<img width="756" alt="image" src="https://github.com/jixiaoyong/ApkSigner/assets/18367427/2cdfe6f1-a97a-4f20-a196-4e435a5d0c93">
