### ISSUE TITLE
[BUG] Windows上无法使用，build-tools和签名配置好后，加固完未签名apk拖动识别路径。当前签名文件显示暂无，v1v2,是否对齐无法勾选

### ISSUE THREAD

**Issue by MhuiHugh** [jixiaoyong/ApkSigner#11]
### 系统类型

Windows

### 系统版本

Windows10

### 软件版本

1.1.3

### 问题描述

加固后可视化单多包签名，问题1.当前选择文件不能多选  2.签名信息已配置，在当前签名文件显示暂无导致v1v2对齐无法勾选  3.保存信息重启软件后丢失  
![捕获](https://github.com/jixiaoyong/ApkSigner/assets/12462349/3261fe70-2fa8-466d-adb7-7560c230659a)
![捕获001](https://github.com/jixiaoyong/ApkSigner/assets/12462349/2551b693-424e-458a-b445-77ea9452f2da)

**Comment by jixiaoyong** [comment]
你好，针对你提到的几个问题：

1.当前选择文件不能多选 （是如何操作的？无法点击后在弹窗选中了多个文件，但是软件只展示了一个吗，还是一个也无法添加）

apk文件通过点击或拖文件到下面的区域添加，如果是点击添加的话，可以试一下在弹窗文件列表中点击apk文件同时按ctrl或者shift实现多选。

![image](https://github.com/jixiaoyong/ApkSigner/assets/18367427/14d65434-7b05-493f-aa65-218982fce29b)


后面两个问题：

2.签名信息已配置，在当前签名文件显示暂无导致v1v2对齐无法勾选 
3.保存信息重启软件后丢失（哪些信息丢失了，比如【签名信息】页面已经保存的签名？

确认【签名APP】页面已选择签名/签名方案/是否对齐无法更新 在windows上存在并已解决，请尝试最新包：https://github.com/jixiaoyong/ApkSigner/releases/tag/v1.2.0-20240426104542-alpha

**Comment by jixiaoyong** [comment]
新版本已经发布，https://github.com/jixiaoyong/ApkSigner/releases/tag/v1.2.0

**Comment by MhuiHugh** [comment]
试了可以正常使用了，感谢老铁
