### ISSUE TITLE
[BUG] mac下 打开提示报错，无法使用。错误信息：sun/misc/unsafe

### ISSUE THREAD

**Issue by womarklee** [jixiaoyong/ApkSigner#13]
### 系统类型

macOS

### 系统版本

13.3.1

### 软件版本

1.2.1

### 问题描述

本地java版本为21，切换为jdk1.8也是同样错误

![img_v3_02b3_e5c59bc5-2ef2-42c4-82da-21975316e65g](https://github.com/jixiaoyong/ApkSigner/assets/27982416/f0f9e88e-dcf4-47ab-a583-15c5c1dcf08f)

### 复现步骤

必现

**Comment by jixiaoyong** [comment]
你好👋，感谢反馈，问题已修复，欢迎下载[新版本v1.2.1-20240521085448-alpha](https://github.com/jixiaoyong/ApkSigner/releases/tag/v1.2.1-20240521085448-alpha)体验。
