### ISSUE TITLE
[BUG] 概述遇到的问题

### ISSUE THREAD

**Issue by opendatacode** [jixiaoyong/ApkSigner#18]
### 系统类型

macOS

### 系统版本

14.6

### 软件版本

1.2.1

## 想要实现的功能
添加apksigner目录报错

## 遇到的问题
apkSigner命令(/Users/xxxx/Library/Android/sdk/build-tools/30.0.3/apksigner)检查失败，请重试（apk signer: exit code: 1

err:The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

）

## 尝试了如下方案，并未解决
java --version
openjdk 17.0.12 2024-07-16

/Users/xxxx/Library/Android/sdk/build-tools/30.0.3/apksigner version
0.9

我的PATH已经添加了java，并且版本是java 17

zipalign就可以添加成功！！！

### 复现步骤

添加文件就提示失败

**Comment by jixiaoyong** [comment]
和问题 https://github.com/jixiaoyong/ApkSigner/issues/17 类似，暂未定位到原因，可关注其进展。
