### ISSUE TITLE
触发了死循环多开的BUG

### ISSUE THREAD

**Issue by LINGMOE-X** [jixiaoyong/ApkSigner#6]
<img width="1124" alt="Screenshot 2024-01-16 165510" src="https://github.com/jixiaoyong/ApkSigner/assets/58373835/d53a3178-c7b2-4938-96d9-d91895f56b03">

刚接触这款软件，在选择apksigner文件的时候选择了本目录中的apksigner程序，导致只要一开软件就疯狂多开。无法关闭。
目前不知道配置文件在哪？正在寻找解决方案。

另外当我从 ``` D:\CommonFolder\SdkForAndroid\build-tools\34.0.0``` 这个目录拖拽时，我只能选择单文件zipalign.exe,无法识别apksigner.bat。

**Comment by LINGMOE-X** [comment]
感谢回答。

我尝试了你说的暂时的方案。发现这个主界面的设置菜单根本无法点击。它是处于一种假死的状态，然后好像每隔0.5秒新开一个窗口，这个窗口是无法关闭的（就是点击了那个关闭窗口的图标无济于事）。打开任务管理器【程序多开太过频繁】也是没法消除的。

而且我也尝试了卸载本软件的方法。发现还是没法改变现状，而且也清除了注册表和jre缓存。估计这和注册表也没啥关联。

目前我只能清空电脑的内存来解决。

**Comment by jixiaoyong** [comment]
我是用虚拟机跑的 window11，可能和真实情况有区别，如果你说的“清空电脑的内存来解决
”可以用的话请暂时这样使用；如果不行的话请先临时卸载掉，等后面修复了再请使用。

实在不好意思，这部分的 ui 提示和逻辑确实有问题，后面考虑加上文件校验和提示。

**Comment by LINGMOE-X** [comment]
哈哈哈，清空电脑内存（重启）就能够关闭本软件了，不是能正常使用了。要不然一直乱蹦，到时候内存直接崩，32G内存都hold不住。😂

已经卸载，目前等待下一次更新中。

附上Windows系统信息：
Edition	Windows 11 Pro
Version	23H2
Installed on	‎2023/‎6/‎11
OS build	22631.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

希望能有所帮助。

**Comment by jixiaoyong** [comment]
> 你好，实在不好意思让你遇到这个问题，针对你说的几个问题：
> 
> 1. 在选择apksigner文件的时候选择了本目录中的apksigner程序，导致只要一开软件就疯狂多开。无法关闭。
> 
> 临时方案：如果你是在“设置信息”->“apk signer 目录” 点击【修改】的时候选择了 ApkSigner软件，可以先在任意一个打开的窗口选择“设置信息”下面的【重置】按钮，然后选择“签名工具配置（不会删除文件）”，并确定删除。
> 
> 我后面会修正这个问题。
> 
> ![image](https://private-user-images.githubusercontent.com/18367427/297013234-f865ae13-1de3-4887-aecc-b9303201c3dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTMyNTAsIm5iZiI6MTcwNTQxMjk1MCwicGF0aCI6Ii8xODM2NzQyNy8yOTcwMTMyMzQtZjg2NWFlMTMtMWRlMy00ODg3LWFlY2MtYjkzMDMyMDFjM2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEzNDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YzA1Yzk3YTc4MTc3NGE0ODAzYWZkYmQ3MWRmMjNiZDE4YTc2Y2NhNGM3YjQ4MWVkNDBmNzcxNTVmMjA3OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i-Vuq0rQX1XQWcA7nfp41l9wM2IezvFc01-XBtsCI88)
> 
> ![SCR-20240116-qeee](https://private-user-images.githubusercontent.com/18367427/297015097-59ccee68-e344-40af-a7b3-e95f8ec1cbaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTMyNTAsIm5iZiI6MTcwNTQxMjk1MCwicGF0aCI6Ii8xODM2NzQyNy8yOTcwMTUwOTctNTljY2VlNjgtZTM0NC00MGFmLWE3YjMtZTk1ZjhlYzFjYmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEzNDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNGFjYWFjNDZmM2M5NjdmYzMxY2Y5MzFlMGFiYjNhMDA5ZTljYzY4NmUzZjg5MDA5ZGI0MjdiMDhiZDAyZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GsVtc4212v8QKzkouMmEfC7oRJJ-wZrrrkW_BBoftlQ)
> 
> 之后再进入Windows 的[“任务管理器”](https://zh.wikihow.com/%E6%89%93%E5%BC%80%E4%BB%BB%E5%8A%A1%E7%AE%A1%E7%90%86%E5%99%A8)，关掉“APK Signer”，然后重新打开即可正常使用。
> 
> ![image](https://private-user-images.githubusercontent.com/18367427/297015877-11134be8-0e69-4c44-9150-37b43db56c73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTMyNTAsIm5iZiI6MTcwNTQxMjk1MCwicGF0aCI6Ii8xODM2NzQyNy8yOTcwMTU4NzctMTExMzRiZTgtMGU2OS00YzQ0LTkxNTAtMzdiNDNkYjU2YzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEzNDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNmIzOTZmNTAwZjhjYTRkOTkzMWMwZTViOWY0MzZjYjBlNzRmODEwMDAzMDhlZDkxZjY2MTEwZGMyMWE4MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JFufRjHy12SnxsIDXhPBsIx-fJrbGu3KT6eVI2Yb5is)
> 
> 2. 目前不知道配置文件在哪？
> 
> 目前没有单独导出的功能，只能在 APP 里面配置或删除
> 
> 3. 当我从  D:\CommonFolder\SdkForAndroid\build-tools\34.0.0 这个目录拖拽时，我只能选择单文件zipalign.exe,无法识别apksigner.bat。
> 
> 这个快捷方式只支持“Android SDK的build-tools的子文件夹到这里，以一次性修改apkSigner和zipAlign目录”，如果单独更新的话，需要点下面的按钮分别更新。

对于第二点修正一下，我刚刚看了一下我保存配置的库的代码，“On Windows, it reads the name of the executable being built and writes to a subkey of HKEY_CURRENT_USER\SOFTWARE using that name.”

    return RegistrySettings("SOFTWARE\\$name")   


Windows电脑上面的配置信息应该是保存在了注册表，类似下面的路径：HKEY_CURRENT_USER\SOFTWARE\AppSigner 里，我现在没在电脑旁没法验证，如果你有空的话可以查看删除掉对应的内容，应该就可以正常用了，或者等我最近的更新（应该就这一两天）。

打开注册表的方式
开始->运行 REGEDIT 打开注册表编辑器,然后依次展开叙述的各项

**Comment by jixiaoyong** [comment]
> 哈哈哈，清空电脑内存（重启）就能够关闭本软件了，不是能正常使用了。要不然一直乱蹦，到时候内存直接崩，32G内存都hold不住。😂
> 
> 已经卸载，目前等待下一次更新中。
> 
> 附上Windows系统信息： Edition Windows 11 Pro Version 23H2 Installed on ‎2023/‎6/‎11 OS build 22631.3007 Experience Windows Feature Experience Pack 1000.22681.1000.0
> 
> 希望能有所帮助。

好的，感谢🙏我尽快修复这个。
